services:
  mysqldb_ferremas:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=SistemaFerremas2024
      - MYSQL_DATABASE=ferremasBD
    volumes:
      - ./bd.sql:/docker-entrypoint-initdb.d/bd.sql
    networks:
      - ferremas_network
    ports:        #SOLO PARA DESAROLLO
      - "3306:3306"


  node_ferremas:
    build: ./backend
    depends_on:
      - mysqldb_ferremas
    networks:
      - ferremas_network
    ports:
      - "3001:3001"

  react_ferremas:
    build: ./frontend
    depends_on:
      - node_ferremas
    networks:
      - ferremas_network
    ports:
      - "3000:3000"

networks:
  ferremas_network: