services:
  mysqldb_ferremas:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=SistemaFerremas2024
      - MYSQL_DATABASE=ferremasBD
    ports:
      - 3306:3306
  node_ferremas:
    build: ./backend
    depends_on:
      - mysqldb_ferremas
    links:
      - mysqldb_ferremas
    ports:
      - 3001:3001
  react_ferremas:
    build: ./frontend
    depends_on:
      - node_ferremas
    links:
      - node_ferremas
    ports:
      - 3000:3000